services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
