apiVersion: v1
kind: Secret
metadata:
  name: word-train-secrets
  labels:
    app: word-train-app
type: Opaque
data:
  SECRET_KEY: UmFuZG9tU2VjcmV0S2V5MTIzIQ==  # base64 encoded "RandomSecretKey123!"
  # Add any other sensitive configuration parameters here
